ubuntu:
	g++ main.cc Ex5_FaceMorphing.cc -o main -std=c++0x -lm -lpthread -lX11 -g -O2
mac:
	clang++ main.cc Ex5_FaceMorphing.cc -o main -std=c++0x -lm -lpthread -L/usr/X11R6/lib -lX11  -g -Wall -O2	
run:
	./main
clean:
	rm main
#all:
#	rm main && g++ main.cc Ex5_FaceMorphing.cc -o main -std=c++0x -lm -lpthread -lX11 -g -O2 && ./main
